var/global/list/gear_datums = list(
	"/obj/item/clothing/glasses/eyepatch",
	"/obj/item/clothing/glasses/monocle",
	"/obj/item/clothing/glasses/regular",
	"/obj/item/clothing/gloves/boxing",
	"/obj/item/clothing/gloves/fingerless",
	"/obj/item/clothing/head/fedora",
	"/obj/item/clothing/head/kitty",
	"/obj/item/clothing/head/soft",
	"/obj/item/clothing/head/ushanka",
	"/obj/item/clothing/mask/cigarette/pipe",
	"/obj/item/clothing/suit/jacket/leather",
	"/obj/item/clothing/tie/red",
	"/obj/item/clothing/tie/scarf/black",
	"/obj/item/device/camera",
	"/obj/item/device/paicard",
	"/obj/item/device/taperecorder",
	"/obj/item/toy/cards/deck",
	"/obj/item/weapon/cane",
	"/obj/item/weapon/coin/iron",
	"/obj/item/weapon/coin/twoheaded",
	"/obj/item/weapon/lighter/zippo",
	"/obj/item/weapon/lipstick/random",
	"/obj/item/weapon/storage/briefcase",
	"/obj/item/weapon/storage/fancy/crayons",
	"/obj/item/weapon/storage/photo_album",
	"/obj/item/weapon/storage/wallet",


										)